FORMAT: 1A
HOST: http://www.google.com

# BoardMVC
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Auth
Authentication API


# Group Post
Post API