FORMAT: 1A
HOST: http://www.google.com

# BoardMVC
Note: this is a draft. The rules and requirements will be finalized on July 1st 2014.

You may have seen TodoMVC which shows the same todo list, created with many different frameworks and libraries.

It's very helpful, but people often find it lacking in common requirements for a web app. It doesn't handle users, persistence, reusable components, modals, AJAX, etc.

TodoMVC helps you quickly weed out the frameworks you don't like, while this allows you to see which you do like at medium scale.

BoardMVC is very similar to Reddit, which is a real site used by many people with all of these requirements. To focus on the front end, a server is provided for you but you can feel free to modify it to fit your framework better.

# Group Auth
Authentication API


# Group Post
Post API